# Generated by Django 5.1.3 on 2024-11-27 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 19, 17, 16, 841950),
                verbose_name="Дата и время начала",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 19, 17, 16, 842275),
                verbose_name="Начало решения",
            ),
        ),
    ]
